apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
    - name: "instance-${ASN_LOCAL}"
      localASN: ${ASN_LOCAL}
      localPort: 179
      peers:
        - name: "r0"
          peerAddress: "${BGP_PEER_ADDRESS}"
          peerASN: ${ASN_PEER}
          peerConfigRef:
            name: "cilium-peer"
