---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-system/kustomization.yaml
  - ./democratic-csi/kustomization.yaml
  #  - ./cert-manager/kustomization.yaml
  - ./flux-system/kustomization.yaml
  - ./monitoring/kustomization.yaml
