---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  namespace: external-secrets
namespace: external-secrets
spec:
  provider:
    infisical:
      hostAPI: https://secrets.lab.vierra.host
      auth:
        universalAuthCredentials:
          clientId:
            name: universal-auth-credentials
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: universal-auth-credentials
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: homelab-tm-pa
        environmentSlug: dev
