---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infisical
  namespace: external-secrets
namespace: external-secrets
resources:
  - ./clustersecretstore.yaml
