---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
  - ./cloudflare/secret.sops.yaml
  - ./helmrelease.yaml
  - ./referencegrant.yaml
  - ./cloudflare/clusterIssuer.yaml
  - ./cloudflare/wildcard-certificate.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=./helm/values.yaml
