# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=./helm/values.yaml
components:
  - ../../../components/envsubst
configurations:
  - ./helm/kustomizeconfig.yaml
  - ./referencegrant.yaml
  - ./cloudflare/secret.sops.yaml
  - ./cloudflare/clusterIssuer.yaml
  - ./cloudflare/wildcard-certificate.yaml
