---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name tuppr
  namespace: &namespace system-upgrades
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubernetes-reflector
  path: ./manifests/apps/system-upgrades/kubernetes-reflector/base
  sourceRef:
    kind: GitRepository
    name: tuppr
    namespace: system-upgrades
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *name
      namespace: *namespace
