apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:1tk4PaTzCfvOVcoTQBnWga0mtIqT3Na3V3+8h8NHWKK34J6MkFz2fKdfRBxy+ss97eyyn+/GWPM=,iv:VVrA7XieOcHMTwGnY/qTswF1QtWj5z4UDpF4f2SEESk=,tag:wGxNuW0CVQ3IrwVEaMX18w==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
sops:
    age:
        - recipient: age1488hlf6e7qc2wtgtv9f92n0zvryzytjw5l9scrg9gg8dfmxwafksdgggy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVzkyc0FUM3RLVGEyZmNF
            TEpuM3FEZnA5VzhtUUowbDR4eGJRcjNQM1dFCnpvdkU5SFBab3IweDhIQ09nM0h4
            NEZybzMxaWFQd0YzZWxMZTYwTkgwVUEKLS0tIFRtS1lZNThSNWdMQzR1VmZKNTd4
            bEc3eWdWRzRIci9oT2lJSzlXNDIrYkUKB024kLtRgHg8L7UguoT6W3cbdqQDkFRt
            C5Mv+l2GkWUhaMI7FMtJ9omNVF12W/mQjQh4FhZ5lSVG/b56zWh3Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ek2lwx2vgqfcaqwkp02mpgttpr2nzmz0ylvgredlzqc3km3weqaqdmsznc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdkg0RFZGQ2RuRTQrSnZB
            Y1JUa1FkdURxSFZ0a2N1OXEyTmJjSFBCQ1JrCjhTSnduZDZwcjBEcjN0dCt1ZkY5
            RnhEemhCZmRoZTdqWnpMSVFYR0MxNzQKLS0tIE9JNzN3SmR3bWxRRDZCZkJZVEpq
            OGZjdllFbXY3VWpMRURJQTlrdjVCbnMKifz6SQJbbvk5YWQr8ahv8rdaA+OBG1iT
            vIMG7Te0RvZIJi/dYkFmeCdvFcHVVsrkuFTsB6ZgKgpu/I8j++h9zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T19:55:05Z"
    mac: ENC[AES256_GCM,data:5F5iPj3CZfV3vCIz/uOeHVIxUfr9+wTLNJ5B35ahU9Z4hpBPoRpWdOGtA8zFSmqeDlOjYV7OX+ReVSvcTAloM+qUQK4lwkaSc7nPulopUpFWRUr1u0+hS/1JV3nEjuunxlxF0eTYD76Ru9FLLV4gSKsUCP18b1JMGgQlpDNOaGk=,iv:yJBGBAAc57fOB4gulhGP1P31ZVH/DjekcJdGk5LE1lg=,tag:dO5LijrsiFRm9OEXyrNr5Q==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.11.0
