---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium.yaml
  - ./democratic-csi.yaml
  - ./emberstack.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./prometheus-community.yaml
  - ./victoriametricsoperator.yaml
