---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoriametricsoperator
spec:
  interval: 15m
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
  ref:
    tag: 0.58.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
