---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps-monitoring-kustomization
namespace: monitoring
components:
  - ../../components/namespace-privileged
resources:
  - ./kube-prometheus-stack/kustomization.yaml
  - ./prometheus-operator-crds/kustomization.yaml
