---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/namespace-privileged
resources:
  - ./prometheus-operator-crds/fluxtomization.yaml
  - ./victoria-metrics/fluxtomization.yaml
  - ./victoriametrics-operator-crds/fluxtomization.yaml
