---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: &namespace flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 30m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: cilium-config
  path: ./manifests/apps/kube-system/cilium-config/base
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
  dependsOn:
    - name: cilium
      namespace: *namespace
