---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  # make sure the component called kustomization
  # has `namespace` field filled
  name: _
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
    kustomize.toolkit.fluxcd.io/prune: "disabled"
