---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps-kube-system-kustomization
namespace: kube-system
resources:
  - ./replicated-resources.yaml
  - ./cilium-operator/kustomization.yaml
  - ./cilium-config/kustomization.yaml
