---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "flux-system/sops-age"
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "flux-system/cluster-secrets"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "flux-system/cluster-settings"
