---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name democratic-csi
  namespace: democratic-csi
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: democratic-csi
  path: ./manifests/apps/democratic-csi/democratic-csi/base/
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *name
      namespace: democratic-csi
  dependsOn:
    - name: flux-mutating-webhook
      namespace: flux-system
