---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cilium
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *name
      namespace: *namespace
  interval: 1h
  path: ./manifests/apps/kube-system/cilium/app
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cilium-config
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  dependsOn:
    - name: cilium
      namespace: *namespace
  interval: 1h
  path: ./manifests/apps/kube-system/cilium/config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cilium-gateway
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: cilium
      namespace: *namespace
    - name: cilium-config
      namespace: *namespace
  interval: 1h
  path: ./manifests/apps/kube-system/cilium/gateway
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
