---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name external-secrets
  namespace: external-secrets
  labels:
    "manifests.vierra.host/file-location": "manifests_apps_external-secrets_external-secrets_kustomization.yaml"
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  path: ./manifests/apps/external-secrets/external-secrets/app
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: external-secrets
