apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s-vierra-host-cert
  namespace: cert-manager
spec:
  secretName: wildcard-k8s-vierra-host-cert
  dnsNames:
    - "*.k8s.vierra.host"
    - "k8s.vierra.host"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-stage
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kube-system"
