apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:32caTSQa/ekxnXqMPyoYodIAAMiBORNY+XuCA0Op91/xUbT1x+ezrw==,iv:tgLocw5flKVRWxzlr2Fmp07thcf+M/2RYPfUZaN8VL4=,tag:zCUdxgQ5X+wt77XCtX8SnA==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - recipient: age1488hlf6e7qc2wtgtv9f92n0zvryzytjw5l9scrg9gg8dfmxwafksdgggy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVzkyc0FUM3RLVGEyZmNF
            TEpuM3FEZnA5VzhtUUowbDR4eGJRcjNQM1dFCnpvdkU5SFBab3IweDhIQ09nM0h4
            NEZybzMxaWFQd0YzZWxMZTYwTkgwVUEKLS0tIFRtS1lZNThSNWdMQzR1VmZKNTd4
            bEc3eWdWRzRIci9oT2lJSzlXNDIrYkUKB024kLtRgHg8L7UguoT6W3cbdqQDkFRt
            C5Mv+l2GkWUhaMI7FMtJ9omNVF12W/mQjQh4FhZ5lSVG/b56zWh3Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ek2lwx2vgqfcaqwkp02mpgttpr2nzmz0ylvgredlzqc3km3weqaqdmsznc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdkg0RFZGQ2RuRTQrSnZB
            Y1JUa1FkdURxSFZ0a2N1OXEyTmJjSFBCQ1JrCjhTSnduZDZwcjBEcjN0dCt1ZkY5
            RnhEemhCZmRoZTdqWnpMSVFYR0MxNzQKLS0tIE9JNzN3SmR3bWxRRDZCZkJZVEpq
            OGZjdllFbXY3VWpMRURJQTlrdjVCbnMKifz6SQJbbvk5YWQr8ahv8rdaA+OBG1iT
            vIMG7Te0RvZIJi/dYkFmeCdvFcHVVsrkuFTsB6ZgKgpu/I8j++h9zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T17:56:59Z"
    mac: ENC[AES256_GCM,data:pzFH8ACeTy2mVUBHkyKtiKRNeNrvOuDs/kiROS4y2hgTkjX3Mo+w7TTZDj3O4o7wQDocsl7E73ywUNUVBnCff06f4HJorYKZEt8Gpjrj/YTwUr7HRz3ncVZGuNjMVp+TGEs387d8Hum4F5PALVczZOUwzWtvJk/VS+A0yACswyg=,iv:F2ZwD8/tik0Hqo1R6k81uOAO/shC4D3O5mXofX6ZQ9A=,tag:A5yaVkpw/nlPZ4gWmnxcjg==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.11.0
