apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
type: Opaque
stringData:
    ASN_LOCAL: ENC[AES256_GCM,data:PtEYmZs=,iv:95IOh+4NMWZBozx2x8d41/Vod/JR7dhOvUl5/gEWJBk=,tag:6ofcstR4xjO+fmTksGmtxA==,type:str]
    ASN_PEER: ENC[AES256_GCM,data:dPrdyiU=,iv:s/MyPKl6YoSlK+dGTZ99xYWiWU3IZf0HZ1NEEOCmC9A=,tag:L2PK/mCxS3+jhJIdx/HrHA==,type:str]
    BGP_PEER_ADDRESS: ENC[AES256_GCM,data:46msZz8RiQGHiiM=,iv:n0hX63U3vXt63EfbqGFnGHMyS7o2A+nXl99pKyKhk/o=,tag:32TBda4+MVIvonITmc+8Tw==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:ANEqAIICdIX1zJ4=,iv:RjbY3Txt+twDBhLFix4w9Hi0n2yzn9PBluHiDUtTroA=,tag:zJiXDE+tvfqysGyvIAG7lQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:mbCB02IaHkUa/JkRerwThUo=,iv:IVsZN/Qr73azY0T22iX1s1X0dBmbOkJ5NsxK6sdsXr4=,tag:VJYMuzsQhM6faOiBAtdZow==,type:str]
    LB_CIDR: ENC[AES256_GCM,data:2WPwvhxF5UfYBD1L1Y8=,iv:vGpj5zwhQibRdKiWplNnpJyh9bOrL7TC6ROfq6cWRsE=,tag:JBlJneqJWDyVZsluHKi2Pw==,type:str]
    NFS_SERVER_IP: ENC[AES256_GCM,data:DAWqeTp7RL537Inw,iv:/fBd6MReWUtiwKJy4+eIXHlH2fWml/1Lfp4xYdlFQjw=,tag:o52MNy8BZ9kpXmUeHZ+k+w==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:CqjzxujJ6KCb4Tyw,iv:7XKCa/LhkCONdj82IhMs1PqTImL0bm6GVYQKkF0SgR8=,tag:DZnL//qo/UTY0I3316bVmw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:HkhcZBOh6FRQI1nlqefNgzF4cCId/pJj+8MApbYmx1u3Gquay7IP8CHQ/iZWdaY2fLNA9BMtIuRQsEyu67ndL0Yb,iv:svv3sdtgNRjxlhpspx+2X1KR0s6+WBrF7km7+Z3iljY=,tag:O4pBoFC4TTqq612wAeIRHQ==,type:str]
    TRUENAS_USERNAME: ENC[AES256_GCM,data:C1M7,iv:m+MNNbtacsCeRRgfVyyVAwPeOCxj3fin9z0VtdumiWg=,tag:H1aZp3qCcHIGJyPQe0R64g==,type:str]
sops:
    age:
        - recipient: age1488hlf6e7qc2wtgtv9f92n0zvryzytjw5l9scrg9gg8dfmxwafksdgggy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETWJ3ak9vMm5zQzRpemdJ
            bEEyUnZ2K3pRdityMFo3aHlwUGM3R2FDa1ZvCnV5Yk56UjlMRkNEM1A2RmhQU1lI
            QmI4WldqOGpLYnhNVitoWlNkYnNML28KLS0tIGIyZFpUbm12Z0JSZWdvb3pVbVpj
            eE1yMlpIRXUvUGp2REpxcHVXaW1VV2sKo4Ov2xoVB4Ug8IFJt/9KGqWUBxHjnjWW
            3sl89dd8qhNSXqRgmd74AfazFpoge75GMayxer7ybfcpS/rXWP4Wig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ek2lwx2vgqfcaqwkp02mpgttpr2nzmz0ylvgredlzqc3km3weqaqdmsznc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU2ttNGtYWUtLWDhwd2Ur
            NUZXMitxdStuWFhKVCt3aU92Y0lvU0ZobDB3CmM3WWhyUzdyQ3FldkJ5c1BVemx2
            SWJoR0txVU50THIyMkx5ejRBSU5SbFEKLS0tIFFYNlNlalgxVkZONVVIa04xRytq
            K2N5TzRQUEI1MmJXSFpQSUE0RWJmUWcKo3Nfg9slcx4gursWM2F52X27sLBCrzJl
            3fb/JU1vzvd5+RjlmS6dIXOF4vJ3N95H+SFV2JyDKILU4W9i0CEMmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T06:37:12Z"
    mac: ENC[AES256_GCM,data:6Z3Lp6U5UwyZJuyt5/ztuZrxVrPMk++V7biXAT188N4+ngCytfAycWQomurHCWxB4pHBE7iIlQ+Q6CbOZSiUve+XcFeaGOsQ/5gJltjEyPGX5JWbmaE2C6PWC1yKo+OFTDtbAGAEra80moldf8jNPeFw12O3VyVBsB23oAFqsh8=,iv:QzInCprE4giZasobwRZmYE50LDnDjcUXrneTsOi7V8o=,tag:r9ZdEwi2QcR3sXwVidaMxA==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.11.0
