---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "10.10.130.100"
  CLUSTER_CIDR: "10.244.0.0/16"
  SERVICE_CIDR: "10.96.0.0/12"
  NODE_CIDR: "10.10.130.0/24"
