apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:0pcuuGx/s7DrzzKTh+4IVtfEXn6Ml7AU,iv:GlPnorQE+IyJ8IVRyC+4QX7SEVpAOh6WKZ21aahV7Fc=,tag:x4QzrslemnarBb1JE0M6UA==,type:str]
    admin-user: ENC[AES256_GCM,data:1xjBIb/8oAY22MRL,iv:Un6M64YERP7haI+xnOhAR2ln8eyN9whKRyma9yiIwe8=,tag:xU/dEUppX+9wnkv887th9w==,type:str]
kind: Secret
metadata:
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
            {"kind":"Secret","apiVersion":"v1","metadata":{"name":"prometheus-user","namespace":"monitoring"},"data":{"admin-password":"M3N3X254Z1lyViNEVkMtQw==","admin-user":"YnZpZXJyYQ=="}}
    name: prometheus-user
    namespace: monitoring
sops:
    age:
        - recipient: age1488hlf6e7qc2wtgtv9f92n0zvryzytjw5l9scrg9gg8dfmxwafksdgggy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d2x0OEVtMTVZWTFoRmNw
            YUxyU0lNa0hHTmNuck1VbFUxTnRmb2ZJd0FvCmxtSkxFREF4bXFZdmd2ZTBzNFEw
            b3ZWRDd4dmRtVFgvYjZqNmFvMTg0ck0KLS0tICtHbnpRMHQyb21OS1hSYjJqZ1Zj
            UUdFNUZRU0ZSVUVYQ3RUMkVGWWYwdkEKcHjwSgok7870/jrNWoWy6Owf5VR2VaWU
            VRGv3UK1hCxc/Bd/vuFU0Yr0iIFe1gd5MhGK3M9vJM8+J+t6FqrJ6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ek2lwx2vgqfcaqwkp02mpgttpr2nzmz0ylvgredlzqc3km3weqaqdmsznc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMnptZDg2a3NTQTNrUjJO
            QjdoamlJU0xRN3VjSjdhVFpkbkZqOTZqbFVBCkZBSlVtR3h2Vllud3kxNFhmR3l6
            eXZhYnJNNHhaVE1jTVl6Nm1MZXFGWVkKLS0tIHAzK1lFVWxYSHovSFJqNDNUQ29Y
            bVRFdm4yMmxHNTRHd0FBRlhKcDlwRFkKlHLYrEhTztpoqqMEigUhzdPGo6Bw5jQ1
            zp0S0/kIHypV1Wla7ZxDvE33FAiTlMw2LTpHkiTjpViNG/ZQsVkY9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T21:45:47Z"
    mac: ENC[AES256_GCM,data:yavg+IN2qRPnfi4EJNXAU9ZIUfFZsyuNhghgfexWQEQCBJwgG6No0G5rADgSQ2iC9p13+WjX7EGaHqrXyyicGEHujLfaGxeMqEwGg2o1eKABNKdk64aYRDVasWQUdyBHHU3bGgryJkVsiK4CK/Vc0Mj8qHWwYiyUY4xaTHgzTuw=,iv:1UNneJmzXEaclR1ebEGxjI/CA2+n/9YDQML649g+MvI=,tag:lPTGQapmVMKD30gGF/9kJA==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.11.0
