apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
type: Opaque
stringData:
    DOMAIN_0: ENC[AES256_GCM,data:ANEqAIICdIX1zJ4=,iv:RjbY3Txt+twDBhLFix4w9Hi0n2yzn9PBluHiDUtTroA=,tag:zJiXDE+tvfqysGyvIAG7lQ==,type:str]
    NFS_SERVER_IP: ENC[AES256_GCM,data:DAWqeTp7RL537Inw,iv:/fBd6MReWUtiwKJy4+eIXHlH2fWml/1Lfp4xYdlFQjw=,tag:o52MNy8BZ9kpXmUeHZ+k+w==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:CqjzxujJ6KCb4Tyw,iv:7XKCa/LhkCONdj82IhMs1PqTImL0bm6GVYQKkF0SgR8=,tag:DZnL//qo/UTY0I3316bVmw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:HkhcZBOh6FRQI1nlqefNgzF4cCId/pJj+8MApbYmx1u3Gquay7IP8CHQ/iZWdaY2fLNA9BMtIuRQsEyu67ndL0Yb,iv:svv3sdtgNRjxlhpspx+2X1KR0s6+WBrF7km7+Z3iljY=,tag:O4pBoFC4TTqq612wAeIRHQ==,type:str]
    TRUENAS_USERNAME: ENC[AES256_GCM,data:C1M7,iv:m+MNNbtacsCeRRgfVyyVAwPeOCxj3fin9z0VtdumiWg=,tag:H1aZp3qCcHIGJyPQe0R64g==,type:str]
sops:
    age:
        - recipient: age1488hlf6e7qc2wtgtv9f92n0zvryzytjw5l9scrg9gg8dfmxwafksdgggy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETWJ3ak9vMm5zQzRpemdJ
            bEEyUnZ2K3pRdityMFo3aHlwUGM3R2FDa1ZvCnV5Yk56UjlMRkNEM1A2RmhQU1lI
            QmI4WldqOGpLYnhNVitoWlNkYnNML28KLS0tIGIyZFpUbm12Z0JSZWdvb3pVbVpj
            eE1yMlpIRXUvUGp2REpxcHVXaW1VV2sKo4Ov2xoVB4Ug8IFJt/9KGqWUBxHjnjWW
            3sl89dd8qhNSXqRgmd74AfazFpoge75GMayxer7ybfcpS/rXWP4Wig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ek2lwx2vgqfcaqwkp02mpgttpr2nzmz0ylvgredlzqc3km3weqaqdmsznc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU2ttNGtYWUtLWDhwd2Ur
            NUZXMitxdStuWFhKVCt3aU92Y0lvU0ZobDB3CmM3WWhyUzdyQ3FldkJ5c1BVemx2
            SWJoR0txVU50THIyMkx5ejRBSU5SbFEKLS0tIFFYNlNlalgxVkZONVVIa04xRytq
            K2N5TzRQUEI1MmJXSFpQSUE0RWJmUWcKo3Nfg9slcx4gursWM2F52X27sLBCrzJl
            3fb/JU1vzvd5+RjlmS6dIXOF4vJ3N95H+SFV2JyDKILU4W9i0CEMmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T23:07:59Z"
    mac: ENC[AES256_GCM,data:TSzYgsLIeCnmEr5qxr9v33bSna12NrXpnIft6dPlZbz9ObDZeX01fgC1vKZLnlDv07Wpvfvukx0YastLr+k0Oasm46tn+uReWbHAmBXKAdwlth8RZyFHLow42JiU6UC5OzKTRDktri+ANridVCDc09Xt9h8dH2sLI4ZpgSMNKpA=,iv:hi4IO4S+7pXGpRdGxD0gKr9w2M9xgV3NU15a0wa/dPA=,tag:jKhoY11/Ao93uMdO6sZRHQ==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.11.0
