apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
type: Opaque
stringData:
    NFS_SERVER_IP: ENC[AES256_GCM,data:K7qB6v1d3UHHuCip,iv:w0Cfeqmt83Bkk/z8CJw1v3tgI2mbYDpcKuY4Dw5+hLo=,tag:5qjQHiJlG/tgdNstVmHR/g==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:mU+rRwyTHj+6ms9D,iv:8QFeBh3Hot1371A95j9fY8IchUrqtP+NtHwjPSeQNZo=,tag:sLKgdo7tb6TnmtZDXoSamQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:4a+IDYzAd0N7ghCIj68NNUnhOKifisX/I95+tPCnge8sFzRY9n7jj8bM9QB+8BkQAwzP7LAGWRudwoii9+Xx2YTm,iv:LZqomAXqDA/rJH6lxZp0L2IMg/V6TiGbN4qBpjM0/TU=,tag:5RMAYiLa/ckKoT/RCYk++g==,type:str]
    TRUENAS_USERNAME: ENC[AES256_GCM,data:4Ybw,iv:hfAMcMR3um6+gkt6/7TB+lvAl2g7sJFIXEaSJfBg4z0=,tag:oNThdFoZgA+fbwmQHzDm6g==,type:str]
sops:
    age:
        - recipient: age1488hlf6e7qc2wtgtv9f92n0zvryzytjw5l9scrg9gg8dfmxwafksdgggy3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS3pBaGt0UndPb01TTlRV
            TWlwOWRSU1JMM2UzUFNZSDNiVmFXSW5OSXpvCnpCVTVpaDFOeTg4SktEYkhNNEww
            d1lVVmhwRnhMMHkwTzFPcmVtOTA0MlkKLS0tIHJaTG5ESHRQU2JmRlFNNllkRVUv
            T1k4QnJZQmo4SUV4c0Fjck5PcWdVUm8K8XNKF0AxXJ8LuVgaz1VD2YLe/ez7VrB3
            MwVOZcxyX6V/UvqZ9JZ8+vlCGvaNSmYluXZGBfXfdEPgh2TMXZgkBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ek2lwx2vgqfcaqwkp02mpgttpr2nzmz0ylvgredlzqc3km3weqaqdmsznc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTFR6bDEvbU9tbmRkWDRo
            QWQySTV1QitsV3RpRlJZYlg4NXh0N1k5bW4wCmtCWURYeGVyNkRxeER2ODl2akJw
            K2x1Y21OYktnd0QxbFlocllaRnVJZ3MKLS0tIEQvRlZJV1daZTZHM0VjMzA0OC9w
            RFhad0tXTVFEcEQ1enFDYWp4dnZSZDgKVnlXIXDczfUmQ0JOlPSY9/QNCW+nWfzR
            We5RV9EZ+HiFserjDv9Afd3wr+gMhP/h5QTdWzbPWozDUgjjK2KDCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T14:26:45Z"
    mac: ENC[AES256_GCM,data:GatwFoM645Wg+4HumBK54IVvAeVxFbVWXgQ3roTE+C5CsVLR+VEe6rBrU4BilxjOi2JdOHEqxPHEYvKm9Z77Qhv0ftYlqj/QFc+6NS+9t6mWMqaeLq+TJ7ZTAhcOYHkjaGuyqI8G8TQB+nUPGHY4ZkkaW3iShTretlGUDmG2yt0=,iv:YeksO/cixE/mBzciHvllpA7A9QD9vFxMhPM3x/Y8KBI=,tag:Rttk1mHZh+vVQ0RddOEMog==,type:str]
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.11.0
